[tool.pdm]
[tool.pdm.dev-dependencies]
dev = ["black>=23.3.0"]

[project]
name = ""
version = ""
description = ""
authors = [{ name = "Іван Ткачук", email = "tkachuk.ivan.v.chnu@edu.ua" }]
dependencies = ["pygame>=2.3.0"]
requires-python = ">=3.10"
license = { text = "MIT" }
